# Site settings
title: 郭华的博客 | Guohua's Blog
header-img: img/home-bg.jpg
email: guohua@hotmail.com
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://guohua.io"
twitter_username: vccore
github_username:  Guohua
facebook_username:  guohua7712
email_username:  guohua@hotmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
